#!/bin/bash

COMMIT_EDITMSG="$1"

addBranchName() {
  NAME=$(git branch | grep '\*' | sed 's/\* //')
  DESCRIPTION=$(git config branch."$NAME".description)
  TOECHO=""
  if [[ "$NAME" != "master" ]] && [[ "$NAME" != "develop" ]]; then
      # extract prefix and number
      numberWithPrefix=$(echo "$NAME" | grep -oE '^[hfFHF]-[0-9]+' | grep -oE '[0-9]+$')
      prefix=$(echo "$NAME" | grep -oE '^[hfFHF]-')
      
      # construct the echo string
      if [[ -n "$numberWithPrefix" ]]; then
          TOECHO="<jira: $numberWithPrefix>"
      fi
  fi
  
  # prepend branch name or JIRA ticket number to commit message
  if [[ -n "$TOECHO" ]]; then
    echo "$TOECHO $(cat "$COMMIT_EDITMSG")" > "$COMMIT_EDITMSG"
  fi
  
  # append branch description to commit message if exists
  if [[ -n "$DESCRIPTION" ]]; then
    echo "" >> "$COMMIT_EDITMSG"
    echo "$DESCRIPTION" >> "$COMMIT_EDITMSG"
  fi 
}

MERGE=$(grep -ic 'merge' "$COMMIT_EDITMSG" | wc -l) # exclude merge commit

if [ "$MERGE" -eq 0 ]; then
  addBranchName
fi
